import Image from "next/image";
import { PageShell } from "@/components/programmes/PageShell";
import { Button } from "@/components/ui/Button";
import "@/app/pages.css";

export const metadata={title:"Data Science Course | Product Hub Africa"};
const curriculum=["Understand the key components of data science and how data solutions are made","Use data tools, Python, Power BI, SQL, Matplotlib and Jupyter Notebooks for analysis","Apply statistics and machine learning techniques to solve real-world problems","Communicate insights effectively through visual storytelling and dashboards"];
const benefits=[
  ["/assets/pages/icon-practical.svg","Practical Session","Practical class sessions to give you the refined experience that helps you get ahead faster"],
  ["/assets/pages/icon-project.svg","Capstone Project","Collaborate with other teams to work on a live project that puts you ahead"],
  ["/assets/pages/icon-certificate.svg","Certification","Get certified after successfully completing the entire programme"],
];
export default function CoursePage(){return <PageShell><div className="inner-page course-page"><section className="course-hero section-shell"><div><span className="pill pill--blue">Data Science</span><h1>Kickstart your career in<br/>Data Science</h1><p>Industry insights and technical guides from Africa’s tech leaders</p><div className="course-tags"><span>Live sessions</span><span>Project Based</span><span>Job Support</span><span>Certification</span></div></div><aside><h2>Data Science</h2><dl><div><dt><Image src="/assets/pages/icon-time.svg" width={18} height={18} alt=""/>Duration</dt><dd>9 Weeks</dd></div><div><dt><Image src="/assets/pages/icon-laptop.svg" width={18} height={18} alt=""/>Method</dt><dd>Virtual Live Class</dd></div><div><dt><Image src="/assets/pages/icon-list.svg" width={18} height={18} alt=""/>Model</dt><dd>Roadmap, Strategy, Agile</dd></div></dl><Button href="/contact?subject=data-science" arrow>Enroll course now</Button></aside></section>
<section className="course-content section-shell"><div className="course-benefits">{benefits.map(([icon,title,copy])=><article key={title}><Image src={icon} width={32} height={32} alt=""/><h3>{title}</h3><p>{copy}</p></article>)}</div><h2>Overview</h2><p>Learning data science extends beyond mastering tools. This programme gives you the analytical thinking, practical experience and confidence to turn information into useful decisions.</p><h2>Learning outcome</h2><ol>{curriculum.map(x=><li key={x}>{x}</li>)}</ol><h2>What You Will Learn (Curriculum)</h2><ol>{curriculum.map(x=><li key={x}>{x}</li>)}</ol><h2>Tools you would get to use</h2><p>During the course of this program, you’ll learn a range of tools that allow you to work confidently with data.</p><div className="tool-row">{["Python","Power BI","SQL","Jupyter","Pandas"].map(x=><span key={x}>{x}</span>)}</div><Button href="/contact?subject=data-science" arrow>Enroll for this course</Button></section>
<section className="course-testimonials"><div className="pha-section-title"><span className="pill pill--blue">Testimonials</span><h2>We deliver value that speaks for itself</h2><p>Here is what our past alumni from the Data Analytics track have to say about our programme.</p></div><div className="testimonial-row">{Array.from({length:4},(_,i)=><article key={i}><div><Image src="/assets/testimonial-1.png" width={48} height={48} alt="Omoseyitan Ojomo"/><p><strong>Omoseyitan Ojomo</strong><span>Graduate</span></p></div><h3>Amazing</h3><p>Every moment of the bootcamp was impactful. I gained practical skills, a stronger professional network and confidence.</p></article>)}</div></section>
<section className="course-faq section-shell"><div className="pha-section-title"><span className="pill pill--blue">FAQs</span><h2>Frequently asked questions</h2><p>Can’t find what you’re looking for? Reach out and let us help.</p><Button href="/contact" size="small" arrow>Contact us</Button></div>{["Can I enroll for this course and take it later?","Are we going to be taught the fundamentals of the tools?","What will be the project once the experience is completed?","Is there a refund if payment is made?"].map((q,i)=><details key={q} open={i===1}><summary>{q}<span/></summary><p>Yes. Our team will share the complete schedule, course requirements and support options before your cohort begins.</p></details>)}</section></div></PageShell>}
